version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mysql_db
    volumes:
      - .:/app

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test_root
      MYSQL_DATABASE: moodofmusic
    ports:
      - "3307:3306" # Expose port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
